"""Business logic and service layer package."""

from app.services.auth_service import (
    register_user,
    login_user,
    format_user_response,
    ensure_user_indexes,
)
from app.services.kyc_service import (
    submit_kyc,
    get_user_kyc,
    get_pending_kyc_list,
    get_kyc_details,
    approve_kyc,
    reject_kyc,
    format_kyc_response,
    ensure_kyc_indexes,
)
from app.services.metal_rates_service import (
    get_rates_public,
    get_rates_admin,
    set_custom_rates,
    refresh_api_rates,
    get_rate_history,
    ensure_rates_initialized,
    get_end_of_day_expiry,
)
from app.services.user_service import (
    get_my_profile,
    update_my_profile,
    get_admin_users,
    get_admin_user_detail,
    update_user_status_by_admin,
    ban_user_by_admin,
    unban_user_by_admin,
)
from app.services.purchase_service import (
    create_purchase,
    get_customer_purchases,
    get_customer_purchase_by_id,
    get_admin_purchases,
    get_admin_purchase_by_id,
    ensure_purchase_indexes,
)
from app.services.holdings_service import (
    get_customer_holdings,
    get_customer_metal_holding,
    get_admin_customer_holdings,
    get_admin_all_holdings,
    process_purchase_for_holdings,
    ensure_holdings_indexes,
)

__all__ = [
    "register_user",
    "login_user",
    "format_user_response",
    "ensure_user_indexes",
    "submit_kyc",
    "get_user_kyc",
    "get_pending_kyc_list",
    "get_kyc_details",
    "approve_kyc",
    "reject_kyc",
    "format_kyc_response",
    "ensure_kyc_indexes",
    "get_rates_public",
    "get_rates_admin",
    "set_custom_rates",
    "refresh_api_rates",
    "get_rate_history",
    "ensure_rates_initialized",
    "get_end_of_day_expiry",
    "get_my_profile",
    "update_my_profile",
    "get_admin_users",
    "get_admin_user_detail",
    "update_user_status_by_admin",
    "ban_user_by_admin",
    "unban_user_by_admin",
    "create_purchase",
    "get_customer_purchases",
    "get_customer_purchase_by_id",
    "get_admin_purchases",
    "get_admin_purchase_by_id",
    "ensure_purchase_indexes",
    "get_customer_holdings",
    "get_customer_metal_holding",
    "get_admin_customer_holdings",
    "get_admin_all_holdings",
    "process_purchase_for_holdings",
    "ensure_holdings_indexes",
]
