"""Pydantic request and response schemas package."""

from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    UserResponse,
    RegisterResponse,
    TokenResponse,
)
from app.schemas.kyc import (
    AddressSchema,
    KYCSubmitRequest,
    KYCRejectRequest,
    KYCResponse,
    AdminKYCPendingItem,
    AdminKYCPendingListResponse,
    AdminKYCUserProfile,
    AdminKYCDetailResponse,
    KYCActionResponse,
)
from app.schemas.rates import (
    MetalRatePublicResponse,
    RatesPublicResponse,
    MetalRateAdminResponse,
    RatesAdminResponse,
    MetalCustomRateInput,
    SetCustomRatesRequest,
    MetalRateSummary,
    RefreshRatesResponse,
    RateHistoryItem,
    RateHistoryResponse,
)
from app.schemas.profile import (
    AddressProfileSchema,
    UserProfileData,
    UserProfileResponse,
    UpdateProfileRequest,
)
from app.schemas.admin_users import (
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserDetailResponse,
    AdminUpdateUserStatusRequest,
    AdminUserStatusResponse,
)
from app.schemas.purchases import (
    CreatePurchaseRequest,
    PurchaseResponse,
    CustomerPurchaseListResponse,
    AdminPurchaseCustomerInfo,
    AdminPurchaseListItem,
    AdminPurchaseListResponse,
    AdminPurchaseDetailResponse,
)

__all__ = [
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserResponse",
    "RegisterResponse",
    "TokenResponse",
    "AddressSchema",
    "KYCSubmitRequest",
    "KYCRejectRequest",
    "KYCResponse",
    "AdminKYCPendingItem",
    "AdminKYCPendingListResponse",
    "AdminKYCUserProfile",
    "AdminKYCDetailResponse",
    "KYCActionResponse",
    "MetalRatePublicResponse",
    "RatesPublicResponse",
    "MetalRateAdminResponse",
    "RatesAdminResponse",
    "MetalCustomRateInput",
    "SetCustomRatesRequest",
    "MetalRateSummary",
    "RefreshRatesResponse",
    "RateHistoryItem",
    "RateHistoryResponse",
    "AddressProfileSchema",
    "UserProfileData",
    "UserProfileResponse",
    "UpdateProfileRequest",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUserDetailResponse",
    "AdminUpdateUserStatusRequest",
    "AdminUserStatusResponse",
    "CreatePurchaseRequest",
    "PurchaseResponse",
    "CustomerPurchaseListResponse",
    "AdminPurchaseCustomerInfo",
    "AdminPurchaseListItem",
    "AdminPurchaseListResponse",
    "AdminPurchaseDetailResponse",
]
